### PR TITLE
Testing models

### PR DESCRIPTION
**Pull request by mehradans92**

### CODE REVIEW

**Comment by mehradans92** [comment]
@whitead Any thoughts on why I cannot load the saved models here?
https://github.com/ur-whitelab/peptide-dashboard/blob/models-test/ml/models_test.ipynb

**Comment by whitead** [comment]
@mehradans92 Aren't you loading the tensorflowJS model into Python? I think you need to load a different file.

**Comment by mehradans92** [comment]
@whitead I think you're talking about having json file that comes from `model.to_json()` and some *.h5 file that comes from `model.save_weights()`.  Seems like stuff saved through `tfjs.converters.save_keras_model(model, "tfjs_model")`, are only loadable in JS and not in Python:(. Unless there's a convertor?

**Comment by whitead** [comment]
I thought you had saved them for python for Ziyue's work?

**Comment by mehradans92** [comment]
@whitead only for the hemolytic model.

**Comment by whitead** [comment]
Ah, well you should save all of them.

**Comment by mehradans92** [comment]
Yeah. This might work:
https://www.tensorflow.org/js/guide/conversion

**Comment by mehradans92** [comment]
Saved keras model in #11

**Pull request closed without merging**
