### PR TITLE
fixed count frequencies in js

### PR DESCRIPTION
**Pull request by mehradans92**

### CODE REVIEW

**Comment by whitead** [comment]
Are you sending frequencies or counts @mehradans92 ?

**Comment by mehradans92** [comment]
@whitead count frequencies.

**Comment by whitead** [comment]
@mehradans92 did you test frequencies vs counts vs frequencies + length? In Rainier's paper we used frequencies + length -- for example `[0.3, 0.1, 0.05, ...., 124]` where the `124` is length of sequence.

**Comment by mehradans92** [comment]
@whitead I have not added length but I can give it a try. So in Rainier's paper this is the line for it:
https://github.com/ur-whitelab/peptide-ai/blob/master/scripts/utils.py#L106
In this code there are frequencies (`tf.compat.v1.reshape(tf.compat.v1.reduce_sum(input_tensor, axis=[1,2]) / float(MAX_LENGTH), [-1, 1])`)  being concatenated with `tf.compat.v1.reduce_mean(input_tensor, axis=1 )`. I am not sure why `reduce_mean` is used. Since `input_tensor` is one-hots, `reduce_sum` , over axis=1 gives the lengths, right?

**Comment by whitead** [comment]
@mehradans92 that was just a shortcut. All peptides are same length and one-hot, so `reduce_mean` returns `L / M` where `M` is max length.

**Comment by mehradans92** [comment]
@whitead adding lengths results lower performance:
```
Old Test auc: 0.8189 - binary_accuracy: 0.8217 (frequencies)

New Test auc: 0.8096 - binary_accuracy: 0.8077 (frequencies + lengths)
```

Could you please check this notebook?
https://nbviewer.org/github/ur-whitelab/peptide-dashboard/blob/counts-tfjs/ml/Hemo_RNN.ipynb

**Review by whitead — APPROVED** [review]

**Comment by mehradans92** [comment]
Tried frequencies + lengths on solubility data, no gain:
```
Test auc: 0.7497 - binary_accuracy: 0.6916   (frequencies)
Test auc: 0.6290 - binary_accuracy: 0.6081   (frequencies + lengths)
Test auc: 0.7408 - binary_accuracy: 0.6797   (frequencies + lengths/190)
```
Will revert to frequencies only.

**Pull request merged**
